version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
